<#
.SYNOPSIS
    Installs Endpoint Management Server as a Windows Service.
.DESCRIPTION
    Automated script for headless server deployment on Windows via PowerShell.
.PARAMETER ListenAddr
    The interface and port the server binds to (default :8443).
.PARAMETER PublicUrl
    The public URL clients and agents use to connect (default http://localhost:8443).
.PARAMETER AdminPassword
    Initial admin password for first bootstrap.
.PARAMETER BinaryPath
    Optional path to server binary. Defaults to search alongside script or repo root.
.PARAMETER InstallDir
    Target directory for server binary. Default is C:\Program Files\EndpointMgmtServer.
.PARAMETER DataDir
    Target directory for configuration and log files. Default is C:\ProgramData\EndpointMgmtServer.
#>
[CmdletBinding()]
param(
    [string]$ListenAddr = ":8443",
    [string]$PublicUrl = "http://localhost:8443",
    [string]$AdminPassword = "",
    [string]$BinaryPath = "",
    [string]$InstallDir = "$env:ProgramFiles\EndpointMgmtServer",
    [string]$DataDir = "$env:ProgramData\EndpointMgmtServer"
)

$ErrorActionPreference = "Stop"

# 1. Require Administrator elevation
$currentPrincipal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Warning "This script requires Administrator privileges. Attempting elevation..."
    $argList = "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`""
    if ($PSBoundParameters.Count -gt 0) {
        foreach ($key in $PSBoundParameters.Keys) {
            $argList += " -$key `"$($PSBoundParameters[$key])`""
        }
    }
    Start-Process powershell.exe -ArgumentList $argList -Verb RunAs
    exit 0
}

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "   Enterprise Endpoint Management Server - PowerShell Installer" -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

# 2. Locate Server Binary
$resolvedBin = $null
$candidates = @(
    $BinaryPath,
    (Join-Path $PSScriptRoot "endpoint-server.exe"),
    (Join-Path $PSScriptRoot "..\..\server-windows-amd64.exe"),
    (Join-Path $PSScriptRoot "..\server-windows-amd64.exe"),
    (Join-Path $InstallDir "endpoint-server.exe")
)
foreach ($c in $candidates) {
    if ($c -and (Test-Path $c)) {
        $resolvedBin = (Resolve-Path $c).Path
        break
    }
}

if (-not $resolvedBin) {
    Write-Error "[-] Could not find server executable ('server-windows-amd64.exe' or 'endpoint-server.exe'). Pass -BinaryPath <path>."
    exit 1
}
Write-Host "[+] Using server binary: $resolvedBin" -ForegroundColor Green

# 3. Create directories
if (-not (Test-Path $InstallDir)) { New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null }
$dbDir = Join-Path $InstallDir "data"
$backupDir = Join-Path $dbDir "backups"
if (-not (Test-Path $dbDir)) { New-Item -ItemType Directory -Path $dbDir -Force | Out-Null }
if (-not (Test-Path $backupDir)) { New-Item -ItemType Directory -Path $backupDir -Force | Out-Null }
if (-not (Test-Path $DataDir)) { New-Item -ItemType Directory -Path $DataDir -Force | Out-Null }

$destExe = Join-Path $InstallDir "endpoint-server.exe"
$envFile = Join-Path $DataDir "server.env"
$dbFile = Join-Path $dbDir "server.db"
$logFile = Join-Path $DataDir "server.log"

# 4. Stop existing service if running
Write-Host "[*] Checking existing Windows Service 'endpoint-mgmt-server'..." -ForegroundColor Yellow
$svc = Get-Service -Name "endpoint-mgmt-server" -ErrorAction SilentlyContinue
if ($svc) {
    Write-Host "    Stopping existing service..." -ForegroundColor Yellow
    Stop-Service -Name "endpoint-mgmt-server" -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
}

# 5. Copy binary
Write-Host "[*] Copying binary to $destExe..." -ForegroundColor Yellow
Copy-Item -Path $resolvedBin -Destination $destExe -Force

# 6. Generate server.env configuration file
Write-Host "[*] Generating runtime configuration: $envFile..." -ForegroundColor Yellow
$envLines = @(
    "# Runtime configuration for endpoint-mgmt-server",
    "# Generated by install-server.ps1",
    "HTTP_ADDR=$ListenAddr",
    "DB_PATH=$dbFile",
    "BACKUP_DIR=$backupDir",
    "LOG_FILE=$logFile",
    "LOG_LEVEL=info",
    "ALLOWED_ORIGIN_DOMAINS=",
    "JWT_SECRET="
)
if ($AdminPassword) {
    $envLines += "ADMIN_PASSWORD=$AdminPassword"
}
[IO.File]::WriteAllLines($envFile, $envLines, [Text.Encoding]::UTF8)

# 7. Configure Windows Firewall
Write-Host "[*] Adding Windows Firewall rule for port $ListenAddr..." -ForegroundColor Cyan
$port = 8443
if ($ListenAddr -match ':(\d+)') {
    $port = [int]$matches[1]
}
try {
    & netsh advfirewall firewall add rule name="Endpoint Management Server" dir=in action=allow protocol=TCP localport=$port profile=any | Out-Null
    Write-Host "[+] Firewall port $port opened." -ForegroundColor Green
} catch {
    Write-Warning "[-] Error configuring Windows Firewall: $_"
}

# 8. Register Windows Service
Write-Host "[*] Registering Windows Service 'endpoint-mgmt-server'..." -ForegroundColor Yellow
if ($svc) {
    & $destExe -service uninstall | Out-Null
    Start-Sleep -Seconds 1
}
& $destExe -env-file $envFile -service install
if ($LASTEXITCODE -ne 0) {
    Write-Warning "[-] Direct service install exited with code $LASTEXITCODE. Trying via sc.exe..."
    & sc.exe create endpoint-mgmt-server binPath= "`"$destExe`" -env-file `"$envFile`"" start= auto DisplayName= "Enterprise Endpoint Management Server"
}

# 9. Start Windows Service
Write-Host "[*] Starting Windows Service 'endpoint-mgmt-server'..." -ForegroundColor Cyan
& $destExe -service start
if ($LASTEXITCODE -ne 0) {
    & sc.exe start endpoint-mgmt-server
}
Start-Sleep -Seconds 2

# 10. Verify Service status
$finalSvc = Get-Service -Name "endpoint-mgmt-server" -ErrorAction SilentlyContinue
if ($finalSvc -and $finalSvc.Status -eq 'Running') {
    Write-Host "[+] Endpoint Management Server is RUNNING." -ForegroundColor Green
} else {
    Write-Warning "[-] Service status: $($finalSvc.Status). Check logs in $logFile."
}

# 11. Registry configuration
try {
    $regKey = "HKLM:\Software\EndpointMgmtServer"
    if (-not (Test-Path $regKey)) { New-Item -Path $regKey -Force | Out-Null }
    Set-ItemProperty -Path $regKey -Name "InstallDir" -Value $InstallDir
    Set-ItemProperty -Path $regKey -Name "EnvFile" -Value $envFile
} catch {}

Write-Host "==========================================================" -ForegroundColor Green
Write-Host "[+] Server Installation Completed Successfully!" -ForegroundColor Green
Write-Host "    Web Console URL: $PublicUrl" -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Green
