package main

import (
	"os"
	"path/filepath"
	"testing"
)

// The service path is the reason this exists: an SCM-launched process has no
// environment block, so its JWT secret and database path arrive only from this
// file. A silent failure here does not crash the server -- it starts with
// whatever the defaults are, which for JWT_SECRET is a refusal to start and for
// DB_PATH is a new empty database the operator did not ask for.
func TestLoadEnvFileAppliesKeyValues(t *testing.T) {
	path := filepath.Join(t.TempDir(), "server.env")
	body := "" +
		"# generated by the server installer\n" +
		"\n" +
		"  HTTP_ADDR = :9443  \n" +
		"DB_PATH=C:\\ProgramData\\EndpointMgmtServer\\data\\server.db\n" +
		"EMPTY_IS_SKIPPED=\n" +
		"LOG_LEVEL=debug\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}

	// Nothing in the ambient environment may leak into this test's assertions,
	// because the "already set wins" rule is about to be exercised.
	for _, k := range []string{"HTTP_ADDR", "DB_PATH", "LOG_LEVEL", "ALREADY_SET"} {
		t.Setenv(k, "")
		os.Unsetenv(k)
	}

	if err := loadEnvFile(path); err != nil {
		t.Fatalf("loadEnvFile: %v", err)
	}

	if got := os.Getenv("HTTP_ADDR"); got != ":9443" {
		t.Errorf("HTTP_ADDR = %q, want :9443 (whitespace around the key and value must be trimmed)", got)
	}
	if got := os.Getenv("DB_PATH"); got != `C:\ProgramData\EndpointMgmtServer\data\server.db` {
		t.Errorf("DB_PATH = %q", got)
	}
	if got := os.Getenv("LOG_LEVEL"); got != "debug" {
		t.Errorf("LOG_LEVEL = %q, want debug", got)
	}
	// A key with no value is a line the installer should never write, and
	// setting it empty would shadow the built-in default.
	if _, ok := os.LookupEnv("EMPTY_IS_SKIPPED"); ok {
		t.Error("an empty value must not be applied")
	}
}

// A real environment variable is an operator's deliberate override. If the
// file won, starting the server by hand to debug a bad setting would silently
// do nothing.
func TestLoadEnvFileDoesNotOverrideARealEnvironmentValue(t *testing.T) {
	path := filepath.Join(t.TempDir(), "server.env")
	if err := os.WriteFile(path, []byte("LOG_LEVEL=info\nHTTP_ADDR=:8443\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("LOG_LEVEL", "debug")

	if err := loadEnvFile(path); err != nil {
		t.Fatal(err)
	}
	if got := os.Getenv("LOG_LEVEL"); got != "debug" {
		t.Errorf("LOG_LEVEL = %q, want the environment's debug -- the file must not win", got)
	}
	// The rest of the file still applies; only the collision is skipped.
	if got := os.Getenv("HTTP_ADDR"); got != ":8443" {
		t.Errorf("HTTP_ADDR = %q, want :8443 from the file", got)
	}
}

// A typo in a generated config file must surface at load time. Silently
// skipping it is how a server ends up listening on the wrong port with a
// default database and no explanation.
func TestLoadEnvFileRejectsAMalformedLine(t *testing.T) {
	path := filepath.Join(t.TempDir(), "server.env")
	if err := os.WriteFile(path, []byte("HTTP_ADDR=:8443\nthis is not a setting\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := loadEnvFile(path); err == nil {
		t.Fatal("a line that is not KEY=VALUE must be an error, not a silent skip")
	}
}

func TestLoadEnvFileReportsAMissingFile(t *testing.T) {
	if err := loadEnvFile(filepath.Join(t.TempDir(), "absent.env")); err == nil {
		t.Fatal("a missing env file must be reported, not treated as empty")
	}
}
